// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc9001.BasketBallRobot;

import org.usfirst.frc9001.BasketBallRobot.commands.AutonomousCommand;
import org.usfirst.frc9001.BasketBallRobot.commands.FeedBall;
import org.usfirst.frc9001.BasketBallRobot.commands.LauncherEnable;
import org.usfirst.frc9001.BasketBallRobot.commands.ManualDrive;
import org.usfirst.frc9001.BasketBallRobot.commands.ManualLauncher;
import org.usfirst.frc9001.BasketBallRobot.subsystems.DriveTrain;
import org.usfirst.frc9001.BasketBallRobot.subsystems.Launcher;
import org.usfirst.frc9001.BasketBallRobot.util.XboxHelper;

import edu.wpi.first.wpilibj.IterativeRobot;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the IterativeRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the manifest file in the resource
 * directory.
 */
public class Robot extends IterativeRobot {

    Command autonomousCommand;
    Command launcherEnable;
    Command feedBall;
    Command manualDrive;
    Command manualLauncher;

    public static OI oi;
    public static DriveTrain driveTrain;
    public static Launcher launcher;

    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    public void robotInit() {
    RobotMap.init();
        driveTrain = new DriveTrain();
        launcher = new Launcher();
        // OI must be constructed after subsystems. If the OI creates Commands 
        //(which it very likely will), subsystems are not guaranteed to be 
        // constructed yet. Thus, their requires() statements may grab null 
        // pointers. Bad news. Don't move it.
        oi = new OI();

        XboxHelper.init();
        launcher.init();
        driveTrain.init();
        
        // instantiate the commands
        autonomousCommand = new AutonomousCommand();
        launcherEnable = new LauncherEnable();
        feedBall = new FeedBall();
        manualDrive = new ManualDrive();
        manualLauncher = new ManualLauncher();
        
        oi.feederEnabler.toggleWhenPressed(feedBall);
        oi.turnOnLauncher.toggleWhenPressed(launcherEnable);
    }

    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    public void disabledInit(){

    }

    public void disabledPeriodic() {
        Scheduler.getInstance().run();
    }

    public void autonomousInit() {
        // schedule the autonomous command (example)
        if (autonomousCommand != null) autonomousCommand.start();
    }

    /**
     * This function is called periodically during autonomous
     */
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
    }

    public void teleopInit() {
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to 
        // continue until interrupted by another command, remove
        // this line or comment it out.
        if (autonomousCommand != null) autonomousCommand.cancel();
    }

    /**
     * This function is called periodically during operator control
     */
    public void teleopPeriodic() {
        Scheduler.getInstance().run();
        
        launcher.logData();
        driveTrain.logData();
        logCommandStatuses();
        
        /* Manual override for testing purposes
        launcher.setLauncherSpeed(1);
        launcher.setLoaderSpeed(1);
        //*/
    }

    /**
     * This function is called periodically during test mode
     */
    public void testPeriodic() {
        LiveWindow.run();
    }
    
    protected void logCommandStatuses() {
    	SmartDashboard.putBoolean("Launcher_Enabled_Running", launcherEnable.isRunning());
    	SmartDashboard.putBoolean("Feed_Ball_Running", feedBall.isRunning());
    	SmartDashboard.putBoolean("Manual_Drive_Running", manualDrive.isRunning());
    	SmartDashboard.putBoolean("Manual_Launcher_Running", manualLauncher.isRunning());
    }
}
